// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ping.sql

package repository

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1 AS ok
`

// Smoke-test query with no table dependency: proves a real round trip
// through pgx to Postgres and back, via sqlc-generated code, without
// assuming any business schema exists yet.
func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
