// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	// Smoke-test query with no table dependency: proves a real round trip
	// through pgx to Postgres and back, via sqlc-generated code, without
	// assuming any business schema exists yet.
	Ping(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
